import type { TRatingItem } from './types';

export const WILL_BE = 'WILL_BE';

export const ratingItems: TRatingItem[] = [
  {
    id: 'series',
    type: 'sticker',
    title: 'Series',
    link: 'https://glimmer-watcher-ab7.notion.site/14d264986432809186f0c779df25f3bc?v=a65acd43535d4fdfb54f3e65b60f20e4',
    color: '#E8A88A',
    rotation: -6,
    desktopPosition: { top: '30%', left: '10%' },
    pinOffset: { x: '40%', y: '20px' },
    order: 1,
  },
  {
    id: 'note',
    type: 'decoration',
    content: 'Note',
    color: '#D9C388',
    rotation: 4,
    desktopPosition: { top: '65%', left: '30%' },
    pinOffset: { x: '65%', y: '25px' },
    order: 2,
  },
  {
    id: 'photo',
    type: 'decoration',
    content: 'Photo',
    color: '#D9C388',
    rotation: 3,
    desktopPosition: { top: '30%', left: '48%' },
    pinOffset: { x: '87%', y: '15px' },
    order: 4,
  },
  {
    id: 'books',
    type: 'sticker',
    title: 'Books',
    link: WILL_BE,
    color: '#8AC6D1',
    rotation: -3,
    desktopPosition: { top: '70%', left: '58%' },
    pinOffset: { x: '30%', y: '10px' },
    order: 3,
  },
  {
    id: 'map',
    type: 'decoration',
    content: 'Map',
    color: '#E0D3B8',
    rotation: -2,
    desktopPosition: { top: '70%', left: '80%' },
    pinOffset: { x: '41%', y: '100px' },
    order: 5,
  },
  {
    id: 'films',
    type: 'sticker',
    title: 'Films',
    link: 'https://glimmer-watcher-ab7.notion.site/14d26498643280e4ab9ce9c78abb65bc?v=3f2a5a428ea84bf485d9f3ec278b02ce',
    color: '#F4D35E',
    rotation: 7,
    desktopPosition: { top: '25%', left: '85%' },
    pinOffset: { x: '30%', y: '15px' },
    order: 6,
  },
];
